### ISSUE TITLE
スタイルファイルを切り出した際に定義されていないsysEXが表示される

### ISSUE THREAD

**Issue by kamekyame** [kamekyame/el-domino_define#10]
http://www.wierzba.homepage.t-online.de/StyleFileDescription_v21.pdf

上記PDFのTable30のようなものがあるらしい。
要確認

**Comment by wakmin-oxo** [comment]
![image](https://user-images.githubusercontent.com/43537352/161430160-6f1c2810-28e2-48a5-b3a8-f50c39cf91b4.png)

**Comment by kamekyame** [comment]
@wakmin-oxo 
僕がスタイルファイル系全然詳しくないのでよくわからないんですが、ここら辺（特にTable 30辺り）ってどういう意味か分かりますか？
![image](https://user-images.githubusercontent.com/47011206/162228708-10703ab9-2c22-4513-8c9d-4e177e3d075c.png)

**Comment by wakmin-oxo** [comment]
元pdfでも"The importance of these sysex is not understood."ですし、
フォーラムでも皆さんわからんって言ってます
https://www.psrtutorial.com/forum/index.php?topic=62519.0

１行目に関してはいくつか種類があるようです
http://electone.blog.jp/archives/5594022.html

**Comment by kamekyame** [comment]
なるほど...
そもそもこのStyle Fileの仕様書も有志の方が作ったものらしいですね...

厳密に定義されていない（特にXG Works Style code）ので、音源定義ファイルに入れるのは見送ろうと思うのですが、どう思いますか？

**Comment by wakmin-oxo** [comment]
私は動作不明でも音源定義ファイルには入れたほうがいいと思います。
音源定義ファイルの強みは「MIDIの低級な部分を利用者が意識しなくても使えるようになる」ところだと思うので、スタイルファイルを取り込んだときに表示されるのがHexだと怖い思いをさせてしまうと思います。
「ここまではわかっているが、ここからはわからない」という部分も含めて、なるべく多くの情報を盛り込んだほうがうれしいと思います。

**Comment by kamekyame** [comment]
なるほど。確かにこういう考え方もありますね…
では入れる方向で行こうかなと思います。
XG Works Style codeですが、見つかっているパターンとしては[ここ](http://electone.blog.jp/archives/5594022.html)に載っているものがほとんどでしょうかね？

**Comment by wakmin-oxo** [comment]
わかりません。。。XGWorksのsysEXがあればいいんですが。
XGWorksはディスコンですし、Table30と[そこ](http://electone.blog.jp/archives/5594022.html)が入っていればとりあえずいいんじゃないかと思います。
もし新規に発見できたら報告します
