### ISSUE TITLE
GM ONが２系統ある

### ISSUE THREAD

**Issue by wakmin-oxo** [kamekyame/el-domino_define#21]
[503]GM ONと[200]GM ONがあります
503のがELS取説からのもので200が親ファイルmu50のものです
どちらも残しておいていいと思いますが、名前は区別がつくようにしたほうがいいと思います

**Comment by wakmin-oxo** [comment]
そしてどうやらこの２つ、sysEXコードが違うっぽい？よくわかりません
ちなみに、[200]でGM ONするように指定したものをエレクトーンに読み込ませ、それを保存した後にEL Data Analyzerで切り出したスタイルファイルでは、[200]でスタイルの初期化をしています。エレクトーン内蔵のスタイルでも同様なのかはわかりません。

**Comment by kamekyame** [comment]
`0x7f`の時はブロードキャストになるそうなので、そのEntryを追加して、統合しました。
mu50との互換性を重視するため、CCM503をCCM200に統合する形にしました。

![image](https://user-images.githubusercontent.com/47011206/162216487-567627f9-50bf-4a8d-adae-6b7ffa752bb5.png)
