### ISSUE TITLE
ドラムセットアップのリセット命令がCCMにない

### ISSUE THREAD

**Issue by wakmin-oxo** [kamekyame/el-domino_define#22]
http://els01stylefile.music.coocan.jp/Stagea_Style/Stagea_Style_P0712.htm
で紹介されているように、
F0H,43H,10H,4CH,08H,08H,07H,03H,F7H
などをスタイルファイルの１小節目に書きますが、これがCCMの解析で出てこないようです。もしかしたらmu50系統には存在しないかもしれないので、追加する必要があるかもしれません。

**Comment by wakmin-oxo** [comment]
![image](https://user-images.githubusercontent.com/43537352/161430100-6ca35633-63c7-44a5-918a-51c23241d701.png)

**Comment by kamekyame** [comment]
MIDIリファレンスではXGパラメーターチェンジ
とまとめて書かれており、引数が3つ以上あったので定義ファイルに含めなかった感じですねー。
分かるものだけ個別に入れておきます

![image](https://user-images.githubusercontent.com/47011206/161897021-77804926-fdde-4465-b32a-7b5f30c5d619.png)

**Comment by kamekyame** [comment]
@wakmin-oxo 
XGの仕様書見ると、DRUMS1～4まで使えるように書いてあります（DRUMS1,2は仕様的に必須）が、エレクトーンでDRUMS3,4は使えるかどうか調べていただくことは可能ですか？
Data`0x01`のDRUMも気になるけど...

![image](https://user-images.githubusercontent.com/47011206/161900538-9eecc446-c3b0-46c6-953a-9480785c94fc.png)

**Comment by wakmin-oxo** [comment]
CASMセクションのほうで三番目以降のドラムキットをどうにかすることができないと思うので、ほぼDRUMS3,4は無理だと思います
可能だとしてもCASMをどのようにすればできるようになるのか全く分からないので時間がかかります

それと、data 0x01 の DRUM はドラムセットアップが存在しないような設定みたいです。エレクトーンの場合は無視していいと思います。
https://jp.yamaha.com/files/download/other_assets/9/321739/read_aoyama.pdf
これの50ページ目に書いてあります

**Comment by kamekyame** [comment]
@wakmin-oxo 
こちらでも調べてみたところ、DRUMは細かい設定ができないだけでドラムの音自体は出るみたいです。
（CH1をDRUMに設定したらCH1からもドラムの音が出た）
DRUM3,4は設定しても反映されなかったので定義ファイルで指定できないようにしておきます
