### ISSUE TITLE
楽器ごとに定義ファイルを分ける

### ISSUE THREAD

**Issue by kamekyame** [kamekyame/el-domino_define#3]

**Comment by wakmin-oxo** [comment]
これについて何かできることはありますか？

**Comment by kamekyame** [comment]
ありがとうございます。
今のところ、音色データのあるELSシリーズとEL900とで分けるつもりです。
多分大丈夫かとは思いますが、両方のmidiリファレンス見て違うところなどあるならばリストアップしてくださると助かります🙏

**Comment by wakmin-oxo** [comment]
ちなみに、memo/ongenTeigiの中にあるやつはコムコムのデータライブラリから持ってきたもので、SoundEffectsのなかにいくつかMSB/LSBが抜けているものがある以外はそのままこの分類でいいような気がしますが、どうですか？

**Comment by kamekyame** [comment]
僕もコムコムのライブラリのサイトをスクレイピングで取ってきているので、大体同じ感じになっていると思います。

```
SoundEffectsのなかにいくつかMSB/LSBが抜けているもの
```
というのは具体的にどの部分でしょうか？

**Comment by wakmin-oxo** [comment]
wakminが作ったmemoのELS02_0.02ではseashore, helicopter, applause1/2, gunshotの<Bank>が抜けています。1514行目などです。

**Comment by kamekyame** [comment]
@wakmin-oxo まだリリースはしていませんが、とりあえず別々の音源定義ファイルに分割しました。

**Comment by wakmin-oxo** [comment]
私は手作業でmap メガボイスを作って、それぞれのPCに1つずつしかバンクが無いような構造にしていました
メガボイスは数が少ないので一度に一覧できても見づらくないと思います
./Mega Voice
./Mega Voice/Mega XX
./Mega Voice/Mega XX/Mega XX
./Mega Voice/Mega YY
./Mega Voice/Mega YY/Mega YY

**Comment by wakmin-oxo** [comment]
だからPC nameをバンクの名前と同じにしてしまうということです

**Comment by wakmin-oxo** [comment]
画像に書いてあるXG Cuttingnoiseはメガボイスでは無いですね
MSB LSB PC=8 0 1のようなものがメガボイスです
いずれにせよPCによる分類が上手くいかないボイスがあるのは、手作業で見つけてPC Nameをバンクと同一にするのが丸いと思います

**Comment by kamekyame** [comment]
@wakmin-oxo 遅くなりましたが、Map変更してmainにマージしました。
