### ISSUE TITLE
CCM色付け

### ISSUE THREAD

**Issue by wakmin-oxo** [kamekyame/el-domino_define#54]
レガシーCCと、重要なCCMの一部は色がほしいです
・重要なCCMの例
EL ON、XG ON
RHYTHM START/STOP
SEQ
とか...

**Comment by kamekyame** [comment]
色分けはどんな感じですると良いでしょう？
○○系は何色
みたいな

**Comment by wakmin-oxo** [comment]
レガシーCCは無難そうな色（青）とか？
EL ON, XG ONは危険そうな色（赤）とか
Drum SetupやEffects parameter changeなど、多数の列で構成されるような大目のメッセージ群は緑とかですかね......
完全に感覚の問題なので適当につけてみて、違和感があったら変える程度でいいような気がします

**Comment by kamekyame** [comment]
なるほど。
mu50の方には元々色が付いているみたいなのですが、どのように色分けしてるんでしょうね…

**Comment by kamekyame** [comment]
@wakmin-oxo 

[Electone_ELS-02.zip](https://github.com/kamekyame/el-domino_define/files/9313795/Electone_ELS-02.zip)

とりあえず現状のxmlです。
mu50の色付けに従って色を変えてみました。
EL ONはXG ONの補色に設定しておきました。

確認お願いしてもらってもよいですか？
他に色変えてほしいところなどもあったら言ってください🙇

**Comment by wakmin-oxo** [comment]
お疲れ様です
付いている色については問題ないと思います
追加で004 2nd EXPと074 Brightnessの色付けをお願いします（何故かついていなかった）
それと、909, 910Rcv Note Off/Onも適当につけていただけると嬉しいです

**Comment by kamekyame** [comment]
僕の環境では、DominoでCCあたりの色付けがされていないのですが、wakminさんの方ではどうでしょうか？(Channel Messageフォルダ以外の色はきちんとついています。)
あと、909,910は色を変えた方がよいでしょうか

![image](https://user-images.githubusercontent.com/47011206/184542849-4f886cc8-5b78-4336-801e-381b69f52a1f.png)

**Comment by wakmin-oxo** [comment]
![image](https://user-images.githubusercontent.com/43537352/184661059-80069491-cc9c-4969-b10b-5772bffb6bf4.png)
自分の環境では、そもそも「コントロールチェンジイベントのプロパティ」ウィンドウでは色は付きません。イベントリストペインに追加することで色が付きます。
レガシーCCは（004, 074以外は）イベントリストでは色がついています。

909, 910は変えたほうが良いです。
909は指定ノートのドラム音を任意のタイミングで止められるようにする（ノートオフを感知する）ための設定で、910はそもそもドラム音をミュートする（ノートオンを無視する）ための設定です。

**Comment by kamekyame** [comment]
環境設定→全般(2)→コントロールチェンジマクロツリーのデザイン→マクロ色を使う
をONにするとコントロールチェンジイベントのプロパティ ウィンドウでも色がつくようになります。

僕のところではCC系だけ色がついてなくて他の部分は色がついているという感じです。
ただ他の音源定義ファイルではCC系も色がついているので、おそらくこの音源定義ファイルが間違っている気がするのですがそれがどこだか...

![image](https://user-images.githubusercontent.com/47011206/184662558-b185fcc2-ff3e-4665-860c-5e221581b3e1.png)

**Comment by wakmin-oxo** [comment]
![image](https://user-images.githubusercontent.com/43537352/184852550-58f2b14d-d3d9-4cf3-8b1d-b74f1838a0ad.png)
なるほど、その設定を有効化したら自分の環境では色が付きました

**Comment by kamekyame** [comment]
wakmin さんのところでは色が付くんですね…
定義ファイルの不備じゃないみたいで良かったです。

残りの色付けだけ変えておきます！

**Comment by kamekyame** [comment]
[Electone_ELS-02.zip](https://github.com/kamekyame/el-domino_define/files/9351820/Electone_ELS-02.zip)

CCM4,74,909,910変更してみました！
（僕の方でCCの色が付かなかったのは単に定義ファイル更新してなかっただけでした。お騒がせしました🙇）

**Comment by wakmin-oxo** [comment]
いい感じだと思います！
