### ISSUE TITLE
TemplateのPanが右に全振りになっている

### ISSUE THREAD

**Issue by wakmin-oxo** [kamekyame/el-domino_define#65]
初歩的なミスですみません。 提供したテンプレートのパンポットが64になっているのですが、これは0が正解かもしれません。
テンプレベースで作ったスタイルをELで読んだところ、全て右マックスになってしまっていました。
修正の方法がわからないためこちらから失礼します。

**Comment by kamekyame** [comment]
@wakmin-oxo  MIDI的には0~127で64が真ん中というのは正しいですが、Dominoの音源定義ファイルではオフセットをかけているので、-64~63の間で指定すればいい感じですね。

**Comment by wakmin-oxo** [comment]
そういうことです。パン-64でランダムになるのはXG仕様にも書いてありますが、エレクトーンで実際鳴るかは試していません。ドラムキットはXG音源だから多分ランダムにできるんじゃないかと思いますが......

**Comment by kamekyame** [comment]
#67 にて直しておきました。Domino上でもわかりやすいようにValueのTableを設定しておきました。
![image](https://user-images.githubusercontent.com/47011206/177465803-a7d49c90-93d0-4192-bd31-839b144f9253.png)
