### ISSUE TITLE
Defaultdataにテンポ、拍子を入れ忘れました

### ISSUE THREAD

**Issue by wakmin-oxo** [kamekyame/el-domino_define#70]
可能であれば1:1:0に追加していただけると幸いです。
もしくは自分がやります

**Comment by kamekyame** [comment]
@wakmin-oxo お願いしてもいいですか？

**Comment by wakmin-oxo** [comment]
わかりました

**Comment by wakmin-oxo** [comment]
確認したところ、wakminがつくったデフォルトデータにはテンポと拍子が入っていました（[template_defaultdata.xml](https://github.com/kamekyame/el-domino_define/blob/main/data/template_defaultdata.xml)）。そのため、統合の段階で抜けてしまっているものと思います。こちら側からはやり方がわからないので、よろしくお願いします。

**Comment by kamekyame** [comment]
なるほど。そういう事でしたか。
確認してみます！

**Comment by kamekyame** [comment]
音源定義ファイルの仕様にTempoタグとTimeSignatureタグの記載がなかったことが原因でした。
ちなみに、TempoタグとTimeSignatureタグの仕様はどこかに書いてあったりしますか？

**Comment by wakmin-oxo** [comment]
デフォルトデータの例に書いてあるだけで仕様は書かれていません
![image](https://user-images.githubusercontent.com/43537352/184515914-7bb863d8-766d-4842-a8c2-2c2de224c41b.png)

まあDominoで指定できるテンポデータの限りは指定できるでしょう

**Comment by kamekyame** [comment]
そうですね。
wakminさんが作ってくださったデータの方（https://github.com/kamekyame/el-domino_define/blob/554e633bce099bc17c928c78151e538ccf4f4a7f/data/template_defaultdata.xml#L36）
ですが、TickではなくMeasによる指定になっているのは間違いでしょうか？

こちらの方で確認してみましたがMeasは認識されないようです

**Comment by wakmin-oxo** [comment]
あら！じゃあ間違いです。Tick指定でお願いします。

**Comment by wakmin-oxo** [comment]
DefaultDataですが、やはりCCM909は外そうと思います。ので自分が後程修正したものを出そうと思います（2本のCCM909を外すだけですが）
