### ISSUE TITLE
テンポの設定に対応するメッセージがない？

### ISSUE THREAD

**Issue by wakmin-oxo** [kamekyame/el-domino_define#77]
エレクトーン本体のテンポのエンコーダーを回すと送信されるsysEXに対応するメッセージがないのか、それとも上手く読み込めてないのか分かりませんが、音源定義で上手く翻訳されていませんでした。

**Comment by kamekyame** [comment]
@wakmin-oxo 遅くなりすみません。
エンコーダを回したときに送られるsysExのデータは複雑で、Dominoでの翻訳に対応していない形式だったので
作ったときに除外したみたいです。

具体的には、
`TL`: テンポの下位2ビットを左に5ビットシフトしたもの。プログラミングてきには `(tempo & 0b11) << 5`
`TH`: テンポの下位2ビット**以外**を右詰めしたもの。プログラミングてきには `(tempo & 0b111111100) >> 2`

という感じです。

**Comment by kamekyame** [comment]
https://github.com/kamekyame/el-domino_define/pull/79 にて、各テンポに対応するValueの値をリストにすることで対応しました。

![image](https://github.com/kamekyame/el-domino_define/assets/47011206/99fc58e5-e67e-40d5-ba86-03162240369f)
